_src_path: /var/home/d/sync/projects/py/hostbutter/src/hostbutter/resources/copier-butterstack
domain: local.hostbutter.net
environment: hostbutter-net
flavor: sweet
kube_context_name: default
release_name: argparse-tui
release_namespace: default
