apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# namespace: default
# namePrefix: dev-
# nameSuffix: "-001"
# labels:
#   - pairs:
#       someName: someValue
#       owner: alice
#       app: bingo
#     includeSelectors: true # <-- false by default
#     includeTemplates: true # <-- false by default

commonAnnotations:
  oncallPager: 800-555-1212

patches:
  - target:
      kind: ServiceAccount
    patch: |-
      - op: add
        path: /imagePullSecrets
        value:
          - name: docker-registry-pull-secrets

# images:
# - name: nginx
#   newName: my.image.registry/nginx
#   newTag: 1.4.0

# replacements:
# - source:
#     kind: Deployment
#     fieldPath: metadata.name
#   targets:
#   - select:
#       name: my-resource
